pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - body~=labels:.*semver-patch.*
    actions:
      merge:
        method: merge
